spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://ep-sparkling-recipe-a2bvthea-pooler.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_C5UOdKenGz1N&sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_C5UOdKenGz1N
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
